#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_LED_PIN PIN_LED
#define PROG_BUTTON_PIN 5

#define KNX_UART_TX_PIN 0
#define KNX_UART_RX_PIN 1

#define CODE_SIZE 5
#define CODE_FLASH_OFFSET 0x80000 //524288